[build]
  publish = "."
  functions = "netlify/functions"
[dev]
  functions = "netlify/functions"
  port = 8888

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/products"
  to   = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/omar"
  to   = "/.netlify/functions/omar"
  status = 200